route:
  receiver: 'discord_webhook'
  repeat_interval: 4h
  group_by: [ alertname ]
  group_wait: 10s
  group_interval: 10s


receivers:
  - name: 'discord_webhook'
    webhook_configs:
      - url: 'http://discord-alerts:9094'