version: '3.7'

services:
  tutor-crm-api:
    container_name: tutor-crm-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '4000:4000'
    networks:
      - monitoring
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: on-failure

  mysql:
    image: mysql:8.0
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./seeders:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
    networks:
      - monitoring

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  mysql_data:
  redis_data:
  alertmanager-data: