const express = require('express');
const router = express.Router();

const userRoutes = require('./userRoutes');
const studentRoutes = require('./studentRoutes');
const teacherRoutes = require('./teacherRoutes');
const subscriptionRoutes = require('./subscriptionRoutes');
const materialRoutes = require('./materialRoutes');
const materialVisibilityStudentRoutes = require('./materialVisibilityStudentRoutes');
const userPhoneRoutes = require('./userPhoneRoutes');
const userReviewRoutes = require('./userReviewRoutes');
const reviewComplaintRoutes = require('./reviewComplaintRoutes');
const blockedUserRoutes = require('./blockedUserRoutes');
const userComplaintRoutes = require('./userComplaintRoutes');
const purchasedMaterialRoutes = require('./purchasedMaterialRoutes');
const saleMaterialFileRoutes = require('./saleMaterialFileRoutes');
const saleMaterialRoutes = require('./saleMaterialRoutes');
const studentCourseRatingRoutes = require('./studentCourseRatingRoutes');
const courseRoutes = require('./courseRoutes');
const locationRoutes = require('./locationRoutes');
const subjectRoutes = require('./subjectRoutes');
const markHistoryRoutes = require('./markHistoryRoutes');
const groupRoutes = require('./groupRoutes');
const groupStudentRoutes = require('./groupStudentRoutes');
const plannedLessonRoutes = require('./plannedLessonRoutes');
const hometaskRoutes = require('./hometaskRoutes');
const hometaskFileRoutes = require('./hometaskFileRoutes');
const doneHometaskRoutes = require('./doneHometaskRoutes');
const doneHometaskFileRoutes = require('./doneHometaskFileRoutes');
const testRoutes = require('./testRoutes');
const testQuestionRoutes = require('./testQuestionRoutes');
const testAnswerRoutes = require('./testAnswerRoutes');
const doneTestRoutes = require('./doneTestRoutes');
const selectedAnswerRoutes = require('./selectedAnswerRoutes');

router.use('/api/users', userRoutes);
router.use('/api/students', studentRoutes);
router.use('/api/teachers', teacherRoutes);
router.use('/api/subscriptions', subscriptionRoutes);
router.use('/api/materials', materialRoutes);
router.use('/api/materialVisibilityStudents', materialVisibilityStudentRoutes);
router.use('/api/userPhones', userPhoneRoutes);
router.use('/api/userReviews', userReviewRoutes);
router.use('/api/reviewComplaints', reviewComplaintRoutes);
router.use('/api/blockedUsers', blockedUserRoutes);
router.use('/api/userComplaints', userComplaintRoutes);
router.use('/api/purchasedMaterials', purchasedMaterialRoutes);
router.use('/api/saleMaterialFiles', saleMaterialFileRoutes);
router.use('/api/saleMaterials', saleMaterialRoutes);
router.use('/api/studentCourseRatings', studentCourseRatingRoutes);
router.use('/api/courses', courseRoutes);
router.use('/api/locations', locationRoutes);
router.use('/api/subjects', subjectRoutes);
router.use('/api/markHistory', markHistoryRoutes);
router.use('/api/groups', groupRoutes);
router.use('/api/groupsStudents', groupStudentRoutes);
router.use('/api/plannedLessons', plannedLessonRoutes);
router.use('/api/hometasks', hometaskRoutes);
router.use('/api/hometaskFiles', hometaskFileRoutes);
router.use('/api/doneHometasks', doneHometaskRoutes);
router.use('/api/doneHometaskFiles', doneHometaskFileRoutes);
router.use('/api/tests', testRoutes);
router.use('/api/testQuestions', testQuestionRoutes);
router.use('/api/testAnswers', testAnswerRoutes);
router.use('/api/doneTests', doneTestRoutes);
router.use('/api/selectedAnswers', selectedAnswerRoutes);

module.exports = router;