global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'tutor-crm-api'
    static_configs:
      - targets: ['tutor-crm-api:4000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['tutor-crm-api-cadvisor:8080']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - alert-rules.yml